name: Terraform CI

on:
  pull_request:
    branches:
      - main

jobs:

  lint:
    name: Terraform Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - run: terraform init
      - run: tflint || echo "::warning file=tflint::TFLint failed"
      - uses: GetTerminus/terraform-pr-commenter@v1
        with:
          file: tflint.log

      - run: terraform fmt -check -recursive || echo "::warning::Terraform fmt failed"
      - run: terraform validate || echo "::warning::Terraform validate failed"

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - run: terraform init
      - uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0

  plan:
    name: Terraform Plan
    needs: [lint, security]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - run: terraform init
      - run: terraform plan -out=tfplan
      - uses: GetTerminus/terraform-pr-commenter@v1
        with:
          file: tfplan

  build_artifact:
    name: Build Artifact
    needs: plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Zip artifact
        run: zip -r terraform-build.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-artifact
          path: terraform-build.zip

      - name: Generate Tag
        id: tag
        run: |
          TAG=$(git tag --sort=-version:refname | head -n 1 | awk -F. '{$NF+=1; print}' OFS=.)
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false

      - uses: mshick/add-pr-comment@v2
        with:
          message: |
            Release created with tag `${{ steps.tag.outputs.tag }}`

