name: Deploy to Prod

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          name: terraform-artifact

      - name: Extract zip
        run: unzip terraform-build.zip

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.0

      - run: terraform init
      - run: terraform plan
      - run: terraform apply -auto-approve
