name: Terraform release
on:
  workflow_dispatch:
    

jobs:
  build_artifact:
    name: Build Artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Zip artifact
        run: zip -r terraform-build.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-artifact
          path: terraform-build.zip

      - uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false

      - uses: mshick/add-pr-comment@v2
        with:
          message: |
            **Release created**
            Tag: `${{ steps.tag.outputs.tag }}`
          repo-token: ${{ secrets.GITHUB_TOKEN }}
